// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: ymnxwmykbvvkyxtbhcep

class SupabaseConfig {
  static const String supabaseUrl = 'https://ymnxwmykbvvkyxtbhcep.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltbnh3bXlrYnZ2a3l4dGJoY2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNDMzNTQsImV4cCI6MjA4NTYxOTM1NH0.cE_PYDkQNQl4X9UGGWb4_H8hul-1hOaFjIWnDlRSBLE';
}
